[project]
name = "morse-echo"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "nicegui>=3.2.0",
    "numpy>=2.3.4",
    "pygobject==3.50.0",
    "pyqt5>=5.15.11",
    "pyqtwebengine>=5.15.7",
    "pywebview>=6.1",
    "qtpy>=2.4.3",
    "sounddevice>=0.5.3",
]
